### ISSUE TITLE
Non ASCII characters in Python source

### ISSUE THREAD

**Issue by rmey** [data-henrik/Bluemix-ServiceBroker#4]
Could not deploy on BMX with latest buildpack.
017-01-11T09:40:04.56+0100 [APP/0]      ERR   File "bmx-sample-broker.py", line 5
2017-01-11T09:40:04.56+0100 [APP/0]      ERR SyntaxError: Non-ASCII character '\xe2' in file bmx-sample-broker.py on line 5, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
I think in the license statement lines in the beginning there are wrong " symbols.

**Comment by rmey** [comment]
Removing the Coyright header solves the issue for me

**Comment by data-henrik** [comment]
@rmey which platform are you on and how did you get the sources (git or download)?

**Comment by data-henrik** [comment]
I reworked the comment section, should be gone. Closing
