### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by carlosbu** [data-henrik/Bluemix-ServiceBroker#6]
Thank you very much for share it ... is it possible to see this new service in catalog if I am in bmx public?

**Comment by data-henrik** [comment]
Bluemix Public only allows to register space-scoped private brokers to regular users. The catalog is not per space, but for your organization. Hence, your service is not shown in the catalog. Once the service is provisioned (using the cf cli), it is shown in the Bluemix dashboard.
